name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install Miri
      run: |
        rustup toolchain install nightly --profile minimal -c miri,rust-src
        cargo +nightly miri setup
    - name: Check formatting
      run: cargo fmt --check
    - name: Run Clippy
      run: cargo clippy --all-features
    - name: Run tests
      run: cargo test --all-features
    - name: Run tests with Miri
      run: cargo +nightly miri test --all-features

  check-specific-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "alloc derive"]
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      run: cargo clippy -F "${{ matrix.features }}"
    - name: Run tests
      run: cargo test -F "${{ matrix.features }}"
